In [1]:
import pandas as pd
import datetime as dt
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
datasets = ['ITV_total_muestra_live.csv', 'ITV_total_muestra_vod.csv', 
            'OPL_total_muestra_live.csv', 'OPL_total_muestra_vod.csv',
            'TVE_DTH_total_muestra_live.csv', 'TVE_DTH_total_muestra_vod.csv']
dfs = pd.DataFrame()

for dataset in range(len(datasets)): 

    df = pd.read_csv('Data/Extraction 3/' + datasets[dataset], sep="\t")
    dfs = pd.concat([dfs, df], ignore_index=True)

cols_names = dfs.columns.str.split('\t')#.tolist()
cols_names = [col for cols_names in cols_names for col in cols_names]

dfs.head()

,user_id,customer_id,subscription_id,unique_user_id,device_id,channel_call_letter,channel_name,channel_type,channel_subtype,program_id,...,profile_id,global_op_id,service_type,capture_day,duration,type,service,offset,buffering,commercialization_type
0,f1b9ff065d526bb021216d90a92455a2f036f26c74ac95...,NaN,NaN,83b2d24add3b48f96edfabfcab903501c5baaf14ab994b...,95faf0c14944c5c29d764cbdb5b74e41b49270b1686e1f...,CHV,CHV,NaN,NaN,267517334,...,0.0,CL,1003,2021-12-19,964,live,ITV,NaN,NaN,NaN
1,f1b9ff065d526bb021216d90a92455a2f036f26c74ac95...,NaN,NaN,83b2d24add3b48f96edfabfcab903501c5baaf14ab994b...,95faf0c14944c5c29d764cbdb5b74e41b49270b1686e1f...,MEGA,MEGA,NaN,NaN,267606959,...,0.0,CL,1003,2021-12-19,1437,live,ITV,NaN,NaN,NaN
2,f1b9ff065d526bb021216d90a92455a2f036f26c74ac95...,NaN,NaN,83b2d24add3b48f96edfabfcab903501c5baaf14ab994b...,95faf0c14944c5c29d764cbdb5b74e41b49270b1686e1f...,MEGA,MEGA,NaN,NaN,264213105,...,0.0,CL,1003,2021-12-19,3338,live,ITV,NaN,NaN,NaN
3,68db52682dcf2f0dff42f36ce26abe2003d87ca76142b4...,NaN,NaN,a85d344894d64c861f7ec7589f6c93640c0e8d42f62ed9...,54e5d381955144c11f5960bdee3d5655ae3f56a0126b5a...,TVN,TVN,NaN,NaN,267607757,...,0.0,CL,1003,2021-12-19,120,live,ITV,NaN,NaN,NaN
4,aabc1623e0307bbaf08c0e85fb507ba08f5f18fe8ad5fe...,NaN,NaN,b43d8a2daa729b5b1384679b73a81334297c90236556a3...,25db36c580cd8105ab3f24fecf8d71d694c006e1aab745...,CHV,CHV,NaN,NaN,267517392,...,0.0,CL,1003,2021-12-19,960,live,ITV,NaN,NaN,NaN

In [3]:
dfs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203065 entries, 0 to 203064
Data columns (total 41 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   user_id                 203065 non-null  object
 1   customer_id             0 non-null       float64
 2   subscription_id         0 non-null       float64
 3   unique_user_id          203065 non-null  object
 4   device_id               203065 non-null  object
 5   channel_call_letter     200546 non-null  object
 6   channel_name            200546 non-null  object
 7   channel_type            0 non-null       float64
 8   channel_subtype         0 non-null       float64
 9   program_id              203065 non-null  int64
 10  program_name            203065 non-null  object
 11  normal_program_name     203065 non-null  object
 12  program_theme           203065 non-null  object
 13  program_subtheme        202711 non-null  object
 14  date_time_start         203065 non-null  object
 15  end_date_time           203065 non-null  object
 16  program_start           200546 non-null  object
 17  program_end             200546 non-null  object
 18  device_type_used        203065 non-null  object
 19  real_start_time         200546 non-null  object
 20  real_session_duration   200546 non-null  float64
 21  global_op_name          203065 non-null  object
 22  service_name            203065 non-null  object
 23  day                     203065 non-null  object
 24  audio_language          285 non-null     object
 25  subs_language           287 non-null     object
 26  producer                1024 non-null    object
 27  distributor             2519 non-null    object
 28  service_source          203065 non-null  int64
 29  service_subtype         203065 non-null  int64
 30  session_type            203065 non-null  int64
 31  profile_id              98164 non-null   float64
 32  global_op_id            203065 non-null  object
 33  service_type            203065 non-null  int64
 34  capture_day             203065 non-null  object
 35  duration                203065 non-null  int64
 36  type                    203065 non-null  object
 37  service                 203065 non-null  object
 38  offset                  506 non-null     float64
 39  buffering               506 non-null     float64
 40  commercialization_type  2519 non-null    float64
dtypes: float64(9), int64(6), object(26)
memory usage: 63.5+ MB

In [4]:
# Drop NA columns
dfs = dfs.drop(['customer_id', 'subscription_id', 'channel_type', 'channel_subtype'], axis=1)

# Change to datetime and integer type
dfs = dfs.astype({"date_time_start":"datetime64", "end_date_time":"datetime64", "real_start_time":"datetime64",
                  "program_start":"datetime64", "program_end":"datetime64", "duration":"int"})

# Delete microseconds
dfs["date_time_start"] = dfs["date_time_start"].apply(lambda x: x.replace(microsecond=0))
dfs["end_date_time"] = dfs["end_date_time"].apply(lambda x: x.replace(microsecond=0))
dfs["real_start_time"] = dfs["real_start_time"].apply(lambda x: x.replace(microsecond=0))
dfs["program_start"] = dfs["program_start"].apply(lambda x: x.replace(microsecond=0))
dfs["program_end"] = dfs["program_end"].apply(lambda x: x.replace(microsecond=0))

# Convert from UTC Timezone to 
dfs["date_time_start"] = dfs["date_time_start"].dt.tz_localize('UTC').dt.tz_convert('Chile/Continental')
dfs["end_date_time"] = dfs["end_date_time"].dt.tz_localize('UTC').dt.tz_convert('Chile/Continental')
dfs["real_start_time"] = dfs["real_start_time"].dt.tz_localize('UTC').dt.tz_convert('Chile/Continental')
dfs["program_start"] = dfs["program_start"].dt.tz_localize('UTC').dt.tz_convert('Chile/Continental')
dfs["program_end"] = dfs["program_end"].dt.tz_localize('UTC').dt.tz_convert('Chile/Continental')

# Eliminate Timezone GMT-3 info from column
dfs["date_time_start"] = dfs["date_time_start"].dt.tz_localize(None)
dfs["end_date_time"] = dfs["end_date_time"].dt.tz_localize(None)
dfs["real_start_time"] = dfs["real_start_time"].dt.tz_localize(None)
dfs["program_start"] = dfs["program_start"].dt.tz_localize(None)
dfs["program_end"] = dfs["program_end"].dt.tz_localize(None)

dfs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203065 entries, 0 to 203064
Data columns (total 37 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   user_id                 203065 non-null  object
 1   unique_user_id          203065 non-null  object
 2   device_id               203065 non-null  object
 3   channel_call_letter     200546 non-null  object
 4   channel_name            200546 non-null  object
 5   program_id              203065 non-null  int64
 6   program_name            203065 non-null  object
 7   normal_program_name     203065 non-null  object
 8   program_theme           203065 non-null  object
 9   program_subtheme        202711 non-null  object
 10  date_time_start         203065 non-null  datetime64[ns]
 11  end_date_time           203065 non-null  datetime64[ns]
 12  program_start           200546 non-null  datetime64[ns]
 13  program_end             200546 non-null  datetime64[ns]
 14  device_type_used        203065 non-null  object
 15  real_start_time         200546 non-null  datetime64[ns]
 16  real_session_duration   200546 non-null  float64
 17  global_op_name          203065 non-null  object
 18  service_name            203065 non-null  object
 19  day                     203065 non-null  object
 20  audio_language          285 non-null     object
 21  subs_language           287 non-null     object
 22  producer                1024 non-null    object
 23  distributor             2519 non-null    object
 24  service_source          203065 non-null  int64
 25  service_subtype         203065 non-null  int64
 26  session_type            203065 non-null  int64
 27  profile_id              98164 non-null   float64
 28  global_op_id            203065 non-null  object
 29  service_type            203065 non-null  int64
 30  capture_day             203065 non-null  object
 31  duration                203065 non-null  int32
 32  type                    203065 non-null  object
 33  service                 203065 non-null  object
 34  offset                  506 non-null     float64
 35  buffering               506 non-null     float64
 36  commercialization_type  2519 non-null    float64
dtypes: datetime64[ns](5), float64(5), int32(1), int64(5), object(21)
memory usage: 56.5+ MB

In [5]:
for i in range(len(dfs.columns)):
#     if len(dfs.iloc[:,i].value_counts()) <5:
    print(dfs.iloc[:,i].value_counts())
#         display(dfs.iloc[:,i])
#     print(dfs.iloc[:,i].name, len(dfs.iloc[:,i].value_counts()))
    
# session_type, profile_id, global_op_id, global_op_name -> 1

966c05753da0434e634fa3a5dca1a28a1b8f2d7a139ac817b85fcaf18268ab71    3515
f52a1d14160e0a3dc4ae9fc8d0eaa4f38e5b962ba1da39d794647646aa010fd1    3335
38250a54d63b60dc5b94aebeb799d4512472f0445528771c4122506caf28422b    2339
d0153f0dfeb79eaa1dbfa3cbe8c96be8a2c609a8ad9b9e233a1ef9f3e9936b47    2277
30c0652b4a989bc26aa689289a2402fc2d1f95325eca32b35b572bd16dfdec22    2265
                                                                    ...
8915add5c4809e2dd33182a315d4c62463908007d74934f7a8d31280d79135d7     161
a8a47d6242ad2b13bf0863386796f0e76e5e41a897ceec33942a0dddc3948be0     139
fe6894dc09ce283e88c35ac91872612f12ca146b383fea3458fa6c5615d59acd     139
5c7ee84027b777d8368238975bdd66cc35a5e85a67a513d3775ab2b4a64bd198     130
fc4d20093159378dd2518b0e92594a5cd6e81285cecb5505982bd4337c39526d     128
Name: user_id, Length: 270, dtype: int64
288a9faaaf554049a0b87e70f52dbffbc6b1239051fb54158cd52f5c432eaa44    3515
97f4e38023e6af568e12164c41c5cd0b880a85ac39709564b4bbe09e4c7ae25e    3335
c1d4d677979001b4c6f365c2179dc225fa1a15039d297160139da30fb9d5a8cf    2339
7e60ad171062740dc57bb7edfc27e9b636a4cdcdfb568e531705e81b684af580    2277
1b1031698019d1abe0a92d869150409305206ebb8110dca132acc866714355d9    2265
                                                                    ...
6a3fba4c5cb3f7311768ab0bd8abc4fbb3d745c8f30ae37d2432a30bc8add9ed     161
f7d67866125337e9593736d6aa37e863346e5ffd1b1e58fb68c3810f966d8a44     139
78f432e3d5f9115ac2f369f0a27976075a4bf54c0f7d5d5879efffee6912566b     139
b9b7ee63828d9dc1107bd4c2119066eeeecb6eece288f6d8e9f7af971adef64f     130
de7de0e2aa31243ea3fa1b367efbb8c14769d1115c3e2192f45c978aafa90bdc     128
Name: unique_user_id, Length: 270, dtype: int64
d0b5c73980feff7d73db28ca7c273324088d9a1a501ec24cc98d9a1294504983    3515
19b5d157cb96019a44b7b8d2a7062847740e7b22b44e9674b81b234ab59a227c    3327
59e2a85feb6df08b96a7fc82678ae2b75c8425ef71eae9fa82d77eb78dd8b1fd    2210
dfd197d495d2a1d67872e31e72076f82cdcffc0c5bc8f04975e0cfc164821820    1760
d853e8e935127cd5eb509c2a19379f05786bef34389020089784570020813eea    1611
                                                                    ...
bc6d83ac9135e173b520e5f82683173d55446a6be9639993f6977fe61c8bd773       1
9a8e0ef0d60cab88a8028f9c4b0a5254c5b497f6ae3557766a5ffd66d74c49d5       1
9a8d0058581e092a2b8929f1f26a7415dca410cf3b09ebcf9de1571cb1625189       1
f5071c7ca840d99163be3b5ffc8942e0be0c33b32db3f770a6fcb8387cc2947a       1
dee68a7e95b9c7baa67b7041bc13e763b14e593053849ba386301ab19abe4cc7       1
Name: device_id, Length: 1587, dtype: int64
MEGA             25349
CHV              18870
Canal 13         11471
TVN              10005
MEGA HD           9379
                 ...
HBO                  2
HBO Mundi            2
HBO Family           2
HBO Signature        1
HBO2                 1
Name: channel_call_letter, Length: 205, dtype: int64
CHV                26755
MEGA               21645
TVN                15282
CANAL 13            9687
MEGA HD             9379
                   ...
STAR HITS              3
HBO FAMILY ESTE        2
HBO MUNDI              2
HBO 2                  1
HBO SIGNATURE          1
Name: channel_name, Length: 235, dtype: int64
262799968    4661
249891867    3504
264569748    2777
249967338    2467
257288521    1940
             ...
267757024       1
267236834       1
266811665       1
266431993       1
266304669       1
Name: program_id, Length: 29831, dtype: int64
POBRE NOVIO                                                        4886
EL TIEMPO                                                          4690
CONTIGO EN LA MAÃ‘ANA                                               4662
MEGANOTICIAS PRIME                                                 4433
CHV NOTICIAS CENTRAL                                               4366
                                                                   ...
MIGHTY MIKE : DUCHESS IN CHARGE                                       1
HORA DE AVENTURA : Â¿PUEDO PASAR?                                      1
BLAZE AND THE MONSTER MACHINE : CONSTRUCTION CREW TO THE RESCUE       1
CARBURANDO CLASIFICACIÃ“N : CLASIFICACIONES TURISMO PISTA Y TCR        1
LAS AVENTURAS DE PILAR : DRAGÃ“N DE LA LLUVIA                          1
Name: program_name, Length: 22712, dtype: int64
Pobre novio                                                         4886
El tiempo                                                           4690
Contigo en la maÃ±ana                                                4662
Meganoticias prime                                                  4433
CHV noticias central                                                4366
                                                                    ...
El increÃ­ble mundo de Gumball : La repeticiÃ³n                          1
La furia : Ohen                                                        1
The Mentalist : Red all over                                           1
Alvinnn!!! And the Chipmunks : Double Dangus, The littlest robot       1
Buddy vs Duff : Mundos antiguos                                        1
Name: normal_program_name, Length: 22810, dtype: int64
MSEPG_SPECIAL            84015
MSEPG_NEWS               46253
MSEPG_MOVIE              20256
MSEPG_SPORTS             18113
MSEPG_SERIES             16936
MSEPG_KIDS               13260
Movie                     1716
MSEPG_PaidProgramming     1703
Episode                    803
MSEPG_SHORTFILM             10
Name: program_theme, dtype: int64
Soccer                                          8527
Reality                                         7718
Drama                                           6042
Interview                                       5659
Drama,Soap                                      5405
                                                ...
Animation,Action,Comedy                            1
Family,Cartoons,Comedy,Children,Animation          1
Comedy,Cartoons,Children,Adventure,Animation       1
Varieties,News,Current Events                      1
Children,Action,Adventure,Animation                1
Name: program_subtheme, Length: 2624, dtype: int64
2021-12-01 21:00:00    98
2021-11-11 21:00:00    95
2021-11-28 21:00:00    94
2021-11-09 21:00:00    92
2021-11-30 21:00:00    91
                       ..
2021-12-25 23:28:32     1
2021-12-26 15:03:46     1
2021-12-31 01:20:39     1
2021-12-20 14:58:48     1
2021-11-07 13:04:24     1
Name: date_time_start, Length: 174449, dtype: int64
2021-11-11 20:59:59    71
2021-11-25 20:59:59    63
2021-11-29 20:59:59    63
2021-12-13 22:00:00    62
2021-11-26 20:59:59    61
                       ..
2021-12-23 18:41:59     1
2021-12-18 21:01:27     1
2021-11-06 02:57:48     1
2021-12-15 15:28:10     1
2021-12-10 13:27:55     1
Name: end_date_time, Length: 175702, dtype: int64
2021-12-13 22:00:00    446
2021-11-29 08:00:00    403
2021-11-23 08:00:00    386
2021-11-28 16:30:00    384
2021-12-19 08:00:00    374
                      ...
2021-11-02 14:48:00      1
2021-12-07 15:16:00      1
2021-11-23 18:56:00      1
2021-12-28 19:24:00      1
2021-11-13 19:39:00      1
Name: program_start, Length: 26517, dtype: int64
2021-12-19 13:00:00    498
2021-11-29 13:00:00    400
2021-11-28 20:30:00    400
2021-11-23 13:00:00    374
2021-12-03 13:00:00    363
                      ...
2021-11-28 11:21:00      1
2021-11-05 18:36:00      1
2021-12-25 01:10:00      1
2021-11-07 19:10:00      1
2021-11-03 03:30:00      1
Name: program_end, Length: 26791, dtype: int64
OpenIPTV_STB          91346
tvLg_no-Accedo        42096
tvSamsung_2017+       32579
tvAndroidTv           16413
sphAndroid             6161
tvSamsung              4770
PC                     2418
tvLg                   2082
Chromecast             1885
stbHybridZapperSat     1328
sphApple                698
tabApple                655
tabAndroid              634
Name: device_type_used, dtype: int64
2021-12-23 21:00:00    242
2021-12-01 21:00:00    226
2021-11-23 21:00:00    215
2021-12-27 21:00:00    209
2021-12-20 21:00:00    207
                      ...
2021-11-30 21:58:54      1
2021-12-01 21:11:29      1
2021-12-02 22:49:44      1
2021-11-06 00:34:13      1
2021-11-01 23:47:02      1
Name: real_start_time, Length: 161805, dtype: int64
120.0      39762
240.0       5132
360.0       3774
600.0       2327
480.0       2289
           ...
11673.0        1
5060.0         1
6717.0         1
5394.0         1
4258.0         1
Name: real_session_duration, Length: 10512, dtype: int64

MOVISTAR CHILE    203065
Name: global_op_name, dtype: int64
Go      111719
IpTv     91346
Name: service_name, dtype: int64
2021-11-11    4262
2021-12-19    4003
2021-11-28    3872
2021-11-03    3753
2021-11-16    3701
              ...
2021-11-13    2827
2021-12-11    2820
2021-11-20    2708
2021-12-25    2508
2021-12-04    2467
Name: day, Length: 61, dtype: int64
spa    279
eng      6
Name: audio_language, dtype: int64
unavailable    248
disabled        32
spa              7
Name: subs_language, dtype: int64
Atreseries                              410
Turner CN                               341
HBO ENTERPRISES                          95
Turner SP                                39
Turner TN                                29
PORTAL_FOXPRE                            25
Inverleigh                               19
Amazon                                   16
Discovery DKIDS                          11
Universal Studios International B.V.      9
Paramount Pictures Global                 8
Discovery ID                              7
Starz_NotOriginal                         6
Warner Bros                               5
TECU_FOXBOTH                              3
Discovery DSC                             1
Name: producer, dtype: int64
TSA                 463
ANTENA3             410
TVN                 145
Nat Geo Kids        121
STAR CHANNEL HD     113
                   ...
DISC. SCIENCE HD      1
CNN Esp               1
SyFy HD               1
Nick Jr               1
AXN                   1
Name: distributor, Length: 87, dtype: int64
2    111719
1     91346
Name: service_source, dtype: int64
102    110391
301     90843
101      1831
Name: service_subtype, dtype: int64
1    203065
Name: session_type, dtype: int64
0.0    98164
Name: profile_id, dtype: int64
CL    203065
Name: global_op_id, dtype: int64
1002    91346
1010    57037
1003    47380
1012     5974
1007     1328
Name: service_type, dtype: int64
2021-11-11    4262
2021-12-19    4003
2021-11-28    3872
2021-11-03    3753
2021-11-16    3701
              ...
2021-11-13    2827
2021-12-11    2820
2021-11-20    2708
2021-12-25    2508
2021-12-04    2467
Name: capture_day, Length: 61, dtype: int64
120     40178
240      5282
360      3933
1800     3010
600      2784
        ...
9162        1
6989        1
4330        1
3990        1
6168        1
Name: duration, Length: 8467, dtype: int64
live    200546
vod       2519
Name: type, dtype: int64
OPL        97320
TVE_DTH    58365
ITV        47380
Name: service, dtype: int64
0.0       298
297.0      58
296.0      35
295.0       9
298.0       5
         ...
332.0       1
461.0       1
463.0       1
426.0       1
2449.0      1
Name: offset, Length: 99, dtype: int64
0.0     501
1.0       3
19.0      1
2.0       1
Name: buffering, dtype: int64
6.0    1495
4.0     838
7.0     123
3.0      41
2.0      22
Name: commercialization_type, dtype: int64

In [6]:
# Drop global_op_id columns since all have the same value
# df_tot = dfs.drop(['global_op_id'], axis=1)

# Drop useless columns ('user_id')
df_tot = dfs.drop(['unique_user_id', 'device_id', 'global_op_name', 'day', 'audio_language', 
                   'subs_language', 'session_type', 'profile_id', 'global_op_id', 'capture_day',
                   'offset', 'buffering', 'commercialization_type', 'producer', 'distributor'], axis=1)

# Drop "repeated columns"
df_tot = df_tot.drop(['real_session_duration', 'real_start_time', 'channel_call_letter', 'normal_program_name'], axis=1)

Drop:
    - **global_op_name**, **session_type**, **profile_id**, **global_op_id** -> Only one value (only useful if different in other countries)
    - **user_id**, **unique_user_id**, **device_id** -> Personal id, not really useful for model and identification in viz not necessary
    - channel_name vs **channel_call_letter** -> Both should be same, but actually not same. (only one stays? Better may be channel_name)
    - program_id -> Might not be useful if we already have the program name (although they not same in values)
    - program_name vs **normal_program_name** -> Both same, only one stays (Better may be program_name)
    - **real_start_time** vs date_time_start -> Does not make sense to keep real_start_time if almost same (Have to check for similarity)
    - program_start, program_end
    - **real_session_duration** vs duration -> Both same, only one stays (Better may be duration)
    - service_name -> May be possible to extract it from device_type_used (Maybe hierarchical?)
    - **day**, **capture_day** -> already have variables with day and time
    - **audio_language**, **subs_language** -> not really populated (could be useful if we actually had it)
    - service_source, service_subtype, service_type, **offset**, **buffering**, **commerzialization_type**, **producer**, **distributor** -> do not really know what it is (have to look into it but does not look good since are not really populated)

In [17]:
# Make classification of device_type_used column values into more general classification
df_tot.loc[df_tot['device_type_used'].isin(['tvLg_no-Accedo', 'tvSamsung_2017+', 
                                            'tvAndroidTv', 'tvSamsung', 'tvLg', 
                                            'tvPanasonic', 'tvPhilips', 'tvSony']), 'device_type_used'] = 'TV'
df_tot.loc[df_tot['device_type_used'].isin(['stbHybridZapperCable', 'stbProteusCableUHD', 
                                            'stbProteusCableHD', 'stbHybridZapperCable1Gb', 
                                            'stbHybridPVRCable', 'stbHybridZapperSat']), 'device_type_used'] = 'STB CATV'
df_tot.loc[df_tot['device_type_used'].isin(['sphAndroid', 'sphApple']), 'device_type_used'] = 'SMARTPHONE'
df_tot.loc[df_tot['device_type_used'].isin(['tabApple', 'tabAndroid', 'tabWin']), 'device_type_used'] = 'TABLET'
df_tot.loc[df_tot['device_type_used'].isin(['Chromecast']), 'device_type_used'] = 'STREAMER'
df_tot.loc[df_tot['device_type_used'].isin(['stbAndroidTv', 'FireTV']), 'device_type_used'] = 'STB OTT'
df_tot.loc[df_tot['device_type_used'].isin(['OpenIPTV_STB', 'Mediaroom']), 'device_type_used'] = 'STB IPTV'

# Change names
df_tot.loc[df_tot['program_theme'].isin(['MSEPG_SPECIAL']), 'program_theme'] = 'LIVE_SPECIAL'
df_tot.loc[df_tot['program_theme'].isin(['MSEPG_NEWS']), 'program_theme'] = 'LIVE_NEWS'
df_tot.loc[df_tot['program_theme'].isin(['MSEPG_MOVIE']), 'program_theme'] = 'LIVE_MOVIE'
df_tot.loc[df_tot['program_theme'].isin(['MSEPG_SPORTS']), 'program_theme'] = 'LIVE_SPORTS'
df_tot.loc[df_tot['program_theme'].isin(['MSEPG_SERIES']), 'program_theme'] = 'LIVE_SERIES'
df_tot.loc[df_tot['program_theme'].isin(['MSEPG_KIDS']), 'program_theme'] = 'LIVE_KIDS'
df_tot.loc[df_tot['program_theme'].isin(['MSEPG_PaidProgramming']), 'program_theme'] = 'LIVE_PAID'
df_tot.loc[df_tot['program_theme'].isin(['MSEPG_SHORTFILM']), 'program_theme'] = 'LIVE_SHORTFILM'
df_tot.loc[df_tot['program_theme'].isin(['Movie']), 'program_theme'] = 'VOD_MOVIE'
df_tot.loc[df_tot['program_theme'].isin(['Episode']), 'program_theme'] = 'VOD_EPISODE'

LIVE_SPECIAL             84015
MSEPG_NEWS               46253
MSEPG_MOVIE              20256
MSEPG_SPORTS             18113
MSEPG_SERIES             16936
MSEPG_KIDS               13260
Movie                     1716
MSEPG_PaidProgramming     1703
Episode                    803
MSEPG_SHORTFILM             10
Name: program_theme, dtype: int64

In [12]:
df_tot.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203065 entries, 0 to 203064
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   user_id           203065 non-null  object
 1   channel_name      200546 non-null  object
 2   program_id        203065 non-null  int64
 3   program_name      203065 non-null  object
 4   program_theme     203065 non-null  object
 5   program_subtheme  202711 non-null  object
 6   date_time_start   203065 non-null  datetime64[ns]
 7   end_date_time     203065 non-null  datetime64[ns]
 8   program_start     200546 non-null  datetime64[ns]
 9   program_end       200546 non-null  datetime64[ns]
 10  device_type_used  203065 non-null  object
 11  service_name      203065 non-null  object
 12  service_source    203065 non-null  int64
 13  service_subtype   203065 non-null  int64
 14  service_type      203065 non-null  int64
 15  duration          203065 non-null  int32
 16  type              203065 non-null  object
 17  service           203065 non-null  object
dtypes: datetime64[ns](4), int32(1), int64(4), object(9)
memory usage: 27.1+ MB

In [13]:
# Create another DataFrame to have only 1 subtheme per row
df_subthemes = df_tot[['user_id', 'channel_name', 'program_theme', 'program_subtheme','date_time_start', 'duration']]

df_subthemes['program_subtheme'] = df_subthemes.program_subtheme.str.split(',')
df_subthemes = df_subthemes.explode('program_subtheme')
df_subthemes

<ipython-input-13-eaab7fab7e8d>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subthemes['program_subtheme'] = df_subthemes.program_subtheme.str.split(',')

,user_id,channel_name,program_theme,program_subtheme,date_time_start,duration
0,f1b9ff065d526bb021216d90a92455a2f036f26c74ac95...,CHV,MSEPG_SPECIAL,Reality,2021-12-18 22:31:22,964
0,f1b9ff065d526bb021216d90a92455a2f036f26c74ac95...,CHV,MSEPG_SPECIAL,Culinary,2021-12-18 22:31:22,964
1,f1b9ff065d526bb021216d90a92455a2f036f26c74ac95...,MEGA,MSEPG_SPECIAL,Interview,2021-12-19 19:57:34,1437
2,f1b9ff065d526bb021216d90a92455a2f036f26c74ac95...,MEGA,MSEPG_NEWS,Interview,2021-12-19 13:01:22,3338
2,f1b9ff065d526bb021216d90a92455a2f036f26c74ac95...,MEGA,MSEPG_NEWS,Politics,2021-12-19 13:01:22,3338
...,...,...,...,...,...,...
203060,dca26f3efdebb610073e5f9dbd79650939c203a7c3d6ea...,NaN,Episode,Thriller,2021-12-25 19:07:21,2647
203061,f0af0e57c20738ec59890239eba5a34dcdd4e00c8cb594...,NaN,Movie,Soap,2021-12-17 21:53:15,121
203062,98359f495d8fc6da7d38225a305b55d779b887adc988fe...,NaN,Movie,Action,2021-11-12 19:26:02,5635
203063,98359f495d8fc6da7d38225a305b55d779b887adc988fe...,NaN,Movie,Action,2021-11-12 21:19:03,326
203064,b29189c880db65d6bcd45249003eda8e94fd836fa66359...,NaN,Movie,Adventure,2021-12-27 13:48:49,66

In [15]:
df_tot.to_csv('Data/Extraction 3/Clean data 3.csv',index=False)
df_subthemes.to_csv('Data/Extraction 3/Subthemes.csv',index=True)